package IMAS.ImasProject.model;

public enum KNotificationType {
    BUS_CREATED,
    BUS_UPDATED,
    BUS_DELETED,
    BUS_STARTED,
    BUS_STOPPED,
    BUS_ROUTE_COMPLETED,
    BUS_ACCIDENT_REPORTED,
    TICKET_ISSUED,
    TICKET_UPDATED,
    TICKET_DELETED,
    TICKET_BOARDED,
    ROUTE_CREATED,
    ROUTE_UPDATED,
    ROUTE_DELETED,
    TASK_ASSIGNED,
    TASK_ACCEPTED,
    TASK_REJECTED,
    TASK_REASSIGNED,
    TASK_COMPLETED
}